services:
  target-server:
    build:
      context: ./target-server
      dockerfile: ./go-target-server/Dockerfile
      # dockerfile: ./python-target-server/Dockerfile
      args:
        - TARGET_SERVER_PORT=${TARGET_SERVER_PORT}
    ports:
      - "${TARGET_SERVER_PORT}:${TARGET_SERVER_PORT}"
    environment:
      - TARGET_SERVER_PORT=${TARGET_SERVER_PORT}
      - TARGET_SERVER_HOST=${TARGET_SERVER_HOST}

  go-proxy:
    build:
      context: ./go-proxy
      args:
        - GO_PROXY_SERVER_PORT=${GO_PROXY_SERVER_PORT}
    ports:
      - "${GO_PROXY_SERVER_PORT}:${GO_PROXY_SERVER_PORT}"
    environment:
      - GO_PROXY_SERVER_PORT=${GO_PROXY_SERVER_PORT}
      - TARGET_SERVER_HOST=target-server
      - TARGET_SERVER_PORT=${TARGET_SERVER_PORT}
      - GO_PROXY_ADMIN_ID=${GO_PROXY_ADMIN_ID}
      - GO_PROXY_ADMIN_SECRET=${GO_PROXY_ADMIN_SECRET}
      - GO_PROXY_REAUTH_COOLDOWN_MS=${GO_PROXY_REAUTH_COOLDOWN_MS}
      - GO_PROXY_RETRY_ATTEMPTS=${GO_PROXY_RETRY_ATTEMPTS}
      - GO_PROXY_RETRY_INTERVAL_MS=${GO_PROXY_RETRY_INTERVAL_MS}
    depends_on:
      - target-server

  java-proxy:
    build:
      context: ./java-proxy
      args:
        - JAVA_PROXY_SERVER_PORT=${JAVA_PROXY_SERVER_PORT}
    ports:
      - "${JAVA_PROXY_SERVER_PORT}:${JAVA_PROXY_SERVER_PORT}"
    environment:
      - JAVA_PROXY_SERVER_PORT=${JAVA_PROXY_SERVER_PORT}
      - TARGET_SERVER_HOST=target-server
      - TARGET_SERVER_PORT=${TARGET_SERVER_PORT}
      - JAVA_PROXY_ADMIN_ID=${JAVA_PROXY_ADMIN_ID}
      - JAVA_PROXY_ADMIN_SECRET=${JAVA_PROXY_ADMIN_SECRET}
      - JAVA_PROXY_REAUTH_COOLDOWN_MS=${JAVA_PROXY_REAUTH_COOLDOWN_MS}
      - JAVA_PROXY_RETRY_ATTEMPTS=${JAVA_PROXY_RETRY_ATTEMPTS}
      - JAVA_PROXY_RETRY_INTERVAL_MS=${JAVA_PROXY_RETRY_INTERVAL_MS}
    depends_on:
      - target-server

  node-proxy:
    build:
      context: ./node-proxy
      args:
        - NODE_PROXY_SERVER_PORT=${NODE_PROXY_SERVER_PORT}
    ports:
      - "${NODE_PROXY_SERVER_PORT}:${NODE_PROXY_SERVER_PORT}"
    environment:
      - NODE_PROXY_SERVER_PORT=${NODE_PROXY_SERVER_PORT}
      - TARGET_SERVER_HOST=target-server
      - TARGET_SERVER_PORT=${TARGET_SERVER_PORT}
      - NODE_PROXY_ADMIN_ID=${NODE_PROXY_ADMIN_ID}
      - NODE_PROXY_ADMIN_SECRET=${NODE_PROXY_ADMIN_SECRET}
      - NODE_PROXY_REAUTH_COOLDOWN_MS=${NODE_PROXY_REAUTH_COOLDOWN_MS}
      - NODE_PROXY_RETRY_ATTEMPTS=${NODE_PROXY_RETRY_ATTEMPTS}
      - NODE_PROXY_RETRY_INTERVAL_MS=${NODE_PROXY_RETRY_INTERVAL_MS}
    depends_on:
      - target-server

  manual-test:
    build:
      context: ./tests/manual
    env_file: .env
    entrypoint: /bin/sh
    command: -c "sleep infinity"
    stdin_open: true
    tty: true
